name: VehiclesRepairConsumableAddon
version: ${project.version}
main: tk.nimari.VehiclesRepairConsumableAddon
api-version: 1.14
depend: [Vehicles, Vault]
authors: [Nimari]
description: An addon made for the Minecraft Vehicles plugin that allows for economy-based vehicle repair.